In [1]:
import tensorflow as  tf
import random

In [2]:
x = tf.placeholder(dtype="float", shape=(2, 5), name='placeholder1')
y = tf.round(x)

with tf.Session() as session:
    output=session.run(y,feed_dict={x:[[2.33,24.24,6.56,7.87,0.55],
                                       [8.24,5.52,75.24,13.95,48.26]]})
    print(output)

[[ 2. 24.  7.  8.  1.]
 [ 8.  6. 75. 14. 48.]]


In [4]:
import numpy as np

In [5]:
matA = tf.placeholder(dtype = 'int32', shape = (3, 3), name = 'MatrixA')
matB = tf.placeholder(dtype = 'int32', shape = (3, 3), name = 'MatrixB')

mat_mul = tf.matmul(matA, matB)

with tf.Session() as session:
    output=session.run(mat_mul,{matA: np.random.randint(0,5,size=(3,3)),
                                matB: np.random.randint(5,10,size=(3,3))})
    print(output)

[[62 74 74]
 [61 64 64]
 [48 45 51]]


In [6]:
str1 = tf.placeholder(dtype = 'string', shape = None, name='String1')
str2 = tf.placeholder(dtype = 'string', shape = None, name='String2')

str_concat =  str1 +" - "+str2

with tf.Session() as session:
    output = session.run(str_concat, {str1: str(input()), 
                                      str2: str(input())})
    print(output)

Only permanent thing
CHANGE
b'Only permanent thing - CHANGE'
