In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
import os
os.chdir('C:/Users/abuze/Great Lakes/Data_Files')
print(os.getcwd())
from sklearn.model_selection import train_test_split

C:\Users\abuze\Great Lakes\Data_Files


In [30]:
import tensorflow as  tf
import random

In [55]:
import tensorflow as  tf

x = tf.placeholder(dtype="float", shape=(2, 5), name='placeholder1')
y = tf.round(x)

with tf.Session() as session:
    output=session.run(y,feed_dict={x:[[2.33,24.24,6.56,7.87,0.55],
                                       [8.24,5.52,75.24,13.95,48.26]]})
    print(output)

[[ 2. 24.  7.  8.  1.]
 [ 8.  6. 75. 14. 48.]]


In [51]:
import tensorflow as tf
import random

matA = tf.placeholder(dtype = 'int32', shape = (3, 3), name = 'MatrixA')
matB = tf.placeholder(dtype = 'int32', shape = (3, 3), name = 'MatrixB')

mat_mul = tf.matmul(matA, matB)

with tf.Session() as session:
    output=session.run(mat_mul,{matA: np.random.randint(0,5,size=(3,3)),
                                matB: np.random.randint(5,10,size=(3,3))})
    print(output)

[[14 18 14]
 [30 34 30]
 [23 25 24]]


In [53]:
import tensorflow as tf

str1 = tf.placeholder(dtype = 'string', shape = None, name='String1')
str2 = tf.placeholder(dtype = 'string', shape = None, name='String2')

str_concat =  str1 +" - "+str2

with tf.Session() as session:
    output = session.run(str_concat, {str1: str(input()), 
                                      str2: str(input())})
    print(output)

CodeSpeedy
Coding Solution & Software Development
b'CodeSpeedy - Coding Solution & Software Development'


In [45]:
x: [[1.323, 224.214, 24.56, 76.87,0.9], 
                                           [48.24, 53.52, 755.24, 13.90545, 048.246]]

In [46]:
type(x)

list